services:
  - type: web
    name: ubumuntu-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: ENVIRONMENT
        value: production
